Fix/#72 Library carousel not responsive
chingu-voyages/v33-bears-team-15 pull request #76
Opened 2021-09-22 18:38 UTC by thomasgilmore95

**Task Description**
Makes the library carousels responsive 

Resolves #72

2021-09-22 18:58 UTC, Kerosz requested changes
I've noticed that now it has too much space between the `cards`. I think that's why I added all those `width` calculations there, to not have that annoying spacing between `cards` when you resize.

![image](https://user-images.githubusercontent.com/31253154/134404626-c821a9b5-c08d-46fe-ac8a-ac4a469e06fb.png)

Also if you add another dataset to that categories data, that only has 2 books in it, this is the displayed result

![image](https://user-images.githubusercontent.com/31253154/134404731-133f737b-d270-47ee-82b3-6dc3a67d1c95.png)

This is the dataset I've added to get the above result:

`data/books.ts`
```js
  {
    category: 'Saved Books',
    link: '/saved',
    data: [
      {
        name: 'Lean Project Management Explained',
        author: 'Can Akdeniz',
        src: 'https://imgv2-2-f.scribdassets.com/img/audiobook_square_badge/399285183/original/216x216/ade11cc8e3/1629025589?v=1',
        rating: 4,
      },
      {
        name: 'Your Next Five Moves: Master the Art of Business Strategy',
        author: 'Patrick Bet-David',
        src: 'https://imgv2-1-f.scribdassets.com/img/audiobook_square_badge/445801005/original/216x216/2c6db4dc9c/1630690492?v=1',
        rating: 5,
      },
    ],
  },
  ```

2021-09-22 19:01 UTC, thomasgilmore95 commented on src/components/library/carousel.tsx
> +  // const widthOffset = data.length > slidesToShow ? 174 : 20 * totalCardsToShow;
Ok

2021-09-22 21:31 UTC, Kerosz commented
@all-contributors please add @thomasgilmore95 for code

2021-09-23 07:19 UTC, Kerosz commented
Closing this as the work has been moved to this PR #79

2021-09-23 07:19 UTC, closed without merging